### PR TITLE
Decrypt

### PR DESCRIPTION
**Pull request by csawe**

### CODE REVIEW

**Comment by csawe** [comment]
Solved inconsistency when '0' appears at the start of the string. #6

**Comment by asenawritescode** [comment]
Great work  !
Working perfectly, currently testing whether the string increases with length in "t" rounds where t >= 32 before integrating into the main project.
Asena XD

**Comment by asenawritescode** [comment]
> Asena XD

String increases in length but we can work with a new hashing algorithm going forward.

**Review by asenawritescode — APPROVED** [review]
Works perfectly ! #1 #3  Both solved in this commit !

**Pull request merged**
